# Generated by Django 3.1.1 on 2020-09-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200920_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.dashboard'),
        ),
    ]
