# Generated by Django 3.1.1 on 2020-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_date_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
