# Generated by Django 3.1.1 on 2020-09-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200921_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingevent',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
