# Generated by Django 3.1.1 on 2020-09-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20200921_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingevent',
            name='nameEvent',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
