# Generated by Django 3.1.1 on 2020-09-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_bookingevent_nameevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingevent',
            name='nameEvent',
        ),
    ]
