# Generated by Django 3.1.1 on 2020-09-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_bookingevent_nameevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
